[aws]
disabled = true

[c]
disabled = true

[git_status]
disabled = true

[nix_shell]
format = 'via [$symbol\($name\)]($style) '
symbol = 'ó±„… '

[custom.agnocast_kmod_version]
command = 'starship_agnocast_kmod'
when = 'starship_agnocast_kmod when'
